name: Run Tests
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Setup SpringBoot
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        uses: npm install
      - name: Run Tests
        uses: npm test
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ./test-results
